src/LinkBuyMvc/Controllers/AuthController.cs
using LinkBuyLibrary.Models;
using LinkBuyLibrary.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkBuyMvc.Controllers
{
    [Route("conta")]
    public class AuthController : Controller
    {
        protected readonly AuthService _authService;

        public AuthController(AuthService authService)
        {
            _authService = authService;
        }

        [HttpGet("entrar")]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("entrar")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel login)
        {
            if (!ModelState.IsValid)
                return View(login);

            var result = await _authService.Login(login);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Produto");
            }

            ModelState.AddModelError("", "Usuário ou senha inválidos");
            return View(login);
        }

        [HttpPost("criar-conta")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel register)
        {
            if (!ModelState.IsValid)
                return View(register);

            var result = await _authService.Register(register);

            if (result > 0)
            {
                return RedirectToAction("Login");
            }

            ModelState.AddModelError("", "Erro ao registrar usuário");
            return View(register);
        }

        [HttpGet("criar-conta")]
        public IActionResult Register()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _authService.Logout();
            return RedirectToAction("Login");
        }
    }
}

src/LinkBuyMvc/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using LinkBuyLibrary.Services;
using LinkBuyLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace LinkBuyMvc.Controllers
{
    [Authorize]
    [Route("categorias")]
    public class CategoriaController : Controller
    {
        private readonly CategoriaService _service;

        public CategoriaController(CategoriaService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllCategoriasAsync());
        }

        [HttpGet("gerenciar/nova-categoria")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("gerenciar/nova-categoria")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descricao")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var result = await _service.CreateCategoriaAsync(categoria);

                if (result > 0)
                {
                    TempData["CategoriaMsgSucesso"] = "Categoria criada com sucesso!";
                    return RedirectToAction(nameof(Index));
                }

                return View(categoria);
            }
            return View(categoria);
        }

        [HttpGet("gerenciar/deletar-categoria")]
        public async Task<IActionResult> Delete(int id)
        {

            var categoria = await _service.GetCategoriasByIdAsync(id);

            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        [HttpPost("gerenciar/deletar-categoria"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoria = await _service.GetCategoriasByIdAsync(id);
            try
            {
                int resultado = 0;
                if (categoria != null)
                {
                    resultado = await _service.DeleteCategoriaAsync(categoria);
                }

                if (resultado > 0)
                {
                    TempData["CategoriaMsgSucesso"] = "Categoria excluida com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                    
                return View(categoria);

            }
            catch (DbUpdateException ex)
            {
                ViewData["MensagemErro"] = "Não é possível excluir uma categoria com produtos associados.";
                return View(categoria);
            }
            catch (Exception ex)
            {
                ViewData["MensagemErro"] = "Ocorreu um erro inesperado.";
                return View(categoria);
            }

        }

        [HttpGet("gerenciar/editar-categoria")]
        public async Task<IActionResult> Edit(int id)
        {
            var categoria = await _service.GetCategoriasByIdAsync(id);

            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        [HttpPost("gerenciar/editar-categoria")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao")] Categoria categoria)
        {
            var resultado = 0;

            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                resultado = await _service.UpdateCategoriaAsync(categoria);

                if (resultado > 0)
                {
                    TempData["CategoriaMsgSucesso"] = "Categoria editada com sucesso!";
                    return RedirectToAction(nameof(Index));
                }
                    
                return View(categoria);
            }

            return View(categoria);
        }

        [HttpGet("gerenciar/detalhes")]
        public async Task<IActionResult> Details(int id)
        {
            var categoria = await _service.GetCategoriasByIdAsync(id);

            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }
    }
}

src/LinkBuyMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkBuy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/LinkBuyMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="color: #5B4ABC;">
            <div class="container-fluid">
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Produto" asp-action="Index">
                            <i class="fa fa-shopping-bag" aria-hidden="true" style="color: #6A0DAD;"></i>
                            <span style="color: #6A0DAD;">LinkBuy</span>
                        </a>
                    }
                    else
                    {
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa fa-shopping-bag" aria-hidden="true" style="color: #6A0DAD;"></i>
                            <span style="color: #6A0DAD;">LinkBuy</span>
                        </a>
                    }
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index" style="color:#6a0dac !important">Produtos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index" style="color:#6a0dac !important">Categorias</a>
                                </li>

                            </ul>

                            <ul class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout" style="color:#6a0dac !important"><i class="fas fa-sign-out-alt me-1"></i>Logout</a>
                                </li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login" style="color:#6a0dac !important">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register" style="color:#6a0dac !important">Cadastrar-se</a>
                                </li>
                            </ul>
                        </div>
                    }
                }
            </div>
        </nav>
    </header>

    <div class="d-flex flex-column min-vh-100" style="margin-bottom:60px;">
        <div class="container">
            <main role="main" class="flex-fill pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            <span style="color: #6A0DAD;">&copy; 2025 - </span>
            <i class="fa fa-shopping-bag" aria-hidden="true" style="color: #6A0DAD;"></i>
            <span style="color: #6A0DAD;"> LinkBuy</span>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>